create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  signal_time timestamptz,
  symbol text not null,
  timeframe text default '5',
  direction text not null check (direction in ('BUY','SELL')),
  mode text,
  entry numeric,
  sl numeric,
  tp1 numeric,
  tp2 numeric,
  tp3 numeric,
  quality numeric,
  result text default 'OPEN' check (result in ('OPEN','WIN','LOSS','BE')),
  exit_price numeric,
  source text default 'TradingView',
  raw jsonb
);

create index if not exists idx_trades_symbol_created_at
on public.trades(symbol, created_at desc);

alter table public.trades enable row level security;

drop policy if exists "public read trades" on public.trades;
create policy "public read trades"
on public.trades
for select
to anon
using (true);
